# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
