# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20181012_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usability', models.FloatField(default=0.0)),
                ('design', models.FloatField(default=0.0)),
                ('creativity', models.FloatField(default=0.0)),
                ('content', models.FloatField(default=0.0)),
                ('mobile', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_rating', to='clone.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_rating', to='clone.Project')),
            ],
        ),
    ]
