# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0004_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='mobile',
        ),
    ]
